import { DarkTheme, DefaultTheme, type Theme } from "@react-navigation/native"

export const THEME = {
  light: {
    background: "hsl(0 0% 98%)",
    foreground: "hsl(0 0% 6%)",
    card: "hsl(0 0% 100%)",
    cardForeground: "hsl(0 0% 6%)",
    popover: "hsl(0 0% 100%)",
    popoverForeground: "hsl(0 0% 6%)",
    primary: "hsl(37 100% 50%)",
    primaryForeground: "hsl(0 0% 100%)",
    secondary: "hsl(37 100% 50%)",
    secondaryForeground: "hsl(0 0% 100%)",
    muted: "hsl(0 0% 74%)",
    mutedForeground: "hsl(0 0% 45%)",
    accent: "hsl(37 100% 50%)",
    accentForeground: "hsl(0 0% 100%)",
    destructive: "hsl(0 84% 60%)",
    destructiveForeground: "hsl(0 0% 100%)",
    border: "hsl(0 0% 88%)",
    input: "hsl(0 0% 88%)",
    ring: "hsl(37 100% 50%)",
    radius: "8px",
  },
  dark: {
    background: "hsl(0 0% 6%)",
    foreground: "hsl(0 0% 98%)",
    card: "hsl(0 0% 10%)",
    cardForeground: "hsl(0 0% 98%)",
    popover: "hsl(0 0% 10%)",
    popoverForeground: "hsl(0 0% 98%)",
    primary: "hsl(37 100% 50%)",
    primaryForeground: "hsl(0 0% 10%)",
    secondary: "hsl(37 100% 50%)",
    secondaryForeground: "hsl(0 0% 10%)",
    muted: "hsl(0 0% 30%)",
    mutedForeground: "hsl(0 0% 64%)",
    accent: "hsl(37 100% 50%)",
    accentForeground: "hsl(0 0% 10%)",
    destructive: "hsl(0 84% 60%)",
    destructiveForeground: "hsl(0 0% 10%)",
    border: "hsl(0 0% 20%)",
    input: "hsl(0 0% 20%)",
    ring: "hsl(37 100% 50%)",
    radius: "8px",
  },
}

export const NAV_THEME: Record<"light" | "dark", Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      ...DefaultTheme.colors,
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      ...DarkTheme.colors,
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
}
